/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AssessorSearchResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssessorSearchResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssessorSearchResult
        //private AssessorSearchResult instance;

        public AssessorSearchResultTests()
        {
            // TODO uncomment below to create an instance of AssessorSearchResult
            //instance = new AssessorSearchResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssessorSearchResult
        /// </summary>
        [Fact]
        public void AssessorSearchResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssessorSearchResult
            //Assert.IsType<AssessorSearchResult>(instance);
        }

        /// <summary>
        /// Test the property 'InviterUserId'
        /// </summary>
        [Fact]
        public void InviterUserIdTest()
        {
            // TODO unit test for the property 'InviterUserId'
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/AssessorSearchResultTests.cs
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FullNameWithEmail'
========
        /// Test the property 'InvitedEmail'
>>>>>>>> 9244e95e4734cf4c95266618eabc5a65b36ffa22:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/InvitationTests.cs
        /// </summary>
        [Fact]
        public void FullNameWithEmailTest()
        {
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/AssessorSearchResultTests.cs
            // TODO unit test for the property 'FullNameWithEmail'
========
            // TODO unit test for the property 'InvitedEmail'
        }

        /// <summary>
        /// Test the property 'InvitedRoles'
        /// </summary>
        [Fact]
        public void InvitedRolesTest()
        {
            // TODO unit test for the property 'InvitedRoles'
        }

        /// <summary>
        /// Test the property 'InvitedAt'
        /// </summary>
        [Fact]
        public void InvitedAtTest()
        {
            // TODO unit test for the property 'InvitedAt'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
>>>>>>>> 9244e95e4734cf4c95266618eabc5a65b36ffa22:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/InvitationTests.cs
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

        /// <summary>
        /// Test the property 'InvitedHnId'
        /// </summary>
        [Fact]
        public void InvitedHnIdTest()
        {
            // TODO unit test for the property 'InvitedHnId'
        }

        /// <summary>
        /// Test the property 'InvitedOrgId'
        /// </summary>
        [Fact]
        public void InvitedOrgIdTest()
        {
            // TODO unit test for the property 'InvitedOrgId'
        }

        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Fact]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }

        /// <summary>
        /// Test the property 'RejectedAt'
        /// </summary>
        [Fact]
        public void RejectedAtTest()
        {
            // TODO unit test for the property 'RejectedAt'
        }

        /// <summary>
        /// Test the property 'ReplacedUserId'
        /// </summary>
        [Fact]
        public void ReplacedUserIdTest()
        {
            // TODO unit test for the property 'ReplacedUserId'
        }

        /// <summary>
        /// Test the property 'RolesToReplace'
        /// </summary>
        [Fact]
        public void RolesToReplaceTest()
        {
            // TODO unit test for the property 'RolesToReplace'
        }
    }
}
