/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ManagedUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManagedUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManagedUserResponse
        //private ManagedUserResponse instance;

        public ManagedUserResponseTests()
        {
            // TODO uncomment below to create an instance of ManagedUserResponse
            //instance = new ManagedUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManagedUserResponse
        /// </summary>
        [Fact]
        public void ManagedUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManagedUserResponse
            //Assert.IsType<ManagedUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Fact]
        public void EmailIdTest()
        {
            // TODO unit test for the property 'EmailId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'HeatNetworks'
        /// </summary>
        [Fact]
        public void HeatNetworksTest()
        {
            // TODO unit test for the property 'HeatNetworks'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'InvitedAt'
        /// </summary>
        [Fact]
        public void InvitedAtTest()
        {
            // TODO unit test for the property 'InvitedAt'
        }
    }
}
