/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ManagedUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManagedUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManagedUserResponse
        //private ManagedUserResponse instance;

        public ManagedUserResponseTests()
        {
            // TODO uncomment below to create an instance of ManagedUserResponse
            //instance = new ManagedUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManagedUserResponse
        /// </summary>
        [Fact]
        public void ManagedUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManagedUserResponse
            //Assert.IsType<ManagedUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'InviterUserId'
        /// </summary>
        [Fact]
        public void InviterUserIdTest()
        {
            // TODO unit test for the property 'InviterUserId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'EmailId'
        /// </summary>
        [Fact]
        public void EmailIdTest()
        {
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/ManagedUserResponseTests.cs
            // TODO unit test for the property 'EmailId'
========
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'InvitedEmail'
        /// </summary>
        [Fact]
        public void InvitedEmailTest()
        {
            // TODO unit test for the property 'InvitedEmail'
        }

        /// <summary>
        /// Test the property 'InvitedRoles'
        /// </summary>
        [Fact]
        public void InvitedRolesTest()
        {
            // TODO unit test for the property 'InvitedRoles'
        }

        /// <summary>
        /// Test the property 'InvitedAt'
        /// </summary>
        [Fact]
        public void InvitedAtTest()
        {
            // TODO unit test for the property 'InvitedAt'
>>>>>>>> dev:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/InvitationTests.cs
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
<<<<<<<< HEAD:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/ManagedUserResponseTests.cs
        /// Test the property 'HeatNetworks'
        /// </summary>
        [Fact]
        public void HeatNetworksTest()
        {
            // TODO unit test for the property 'HeatNetworks'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'InvitedAt'
        /// </summary>
        [Fact]
        public void InvitedAtTest()
        {
            // TODO unit test for the property 'InvitedAt'
========
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

        /// <summary>
        /// Test the property 'InvitedHnId'
        /// </summary>
        [Fact]
        public void InvitedHnIdTest()
        {
            // TODO unit test for the property 'InvitedHnId'
        }

        /// <summary>
        /// Test the property 'InvitedOrgId'
        /// </summary>
        [Fact]
        public void InvitedOrgIdTest()
        {
            // TODO unit test for the property 'InvitedOrgId'
        }

        /// <summary>
        /// Test the property 'AcceptedAt'
        /// </summary>
        [Fact]
        public void AcceptedAtTest()
        {
            // TODO unit test for the property 'AcceptedAt'
        }

        /// <summary>
        /// Test the property 'RejectedAt'
        /// </summary>
        [Fact]
        public void RejectedAtTest()
        {
            // TODO unit test for the property 'RejectedAt'
        }

        /// <summary>
        /// Test the property 'ReplacedUserId'
        /// </summary>
        [Fact]
        public void ReplacedUserIdTest()
        {
            // TODO unit test for the property 'ReplacedUserId'
        }

        /// <summary>
        /// Test the property 'RolesToReplace'
        /// </summary>
        [Fact]
        public void RolesToReplaceTest()
        {
            // TODO unit test for the property 'RolesToReplace'
>>>>>>>> dev:HNTAS/HNTAS.Api.Client/src/HNTAS.Api.Client.Test/Model/InvitationTests.cs
        }
    }
}
