/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PagedResultOfHeatNetworkResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PagedResultOfHeatNetworkResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PagedResultOfHeatNetworkResponse
        //private PagedResultOfHeatNetworkResponse instance;

        public PagedResultOfHeatNetworkResponseTests()
        {
            // TODO uncomment below to create an instance of PagedResultOfHeatNetworkResponse
            //instance = new PagedResultOfHeatNetworkResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PagedResultOfHeatNetworkResponse
        /// </summary>
        [Fact]
        public void PagedResultOfHeatNetworkResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PagedResultOfHeatNetworkResponse
            //Assert.IsType<PagedResultOfHeatNetworkResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }

        /// <summary>
        /// Test the property 'HasPreviousPage'
        /// </summary>
        [Fact]
        public void HasPreviousPageTest()
        {
            // TODO unit test for the property 'HasPreviousPage'
        }

        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Fact]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
    }
}
