/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HNTAS.Api.Client.Model;
using HNTAS.Api.Client.Client;
using System.Reflection;

namespace HNTAS.Api.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserNetworkDetailsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserNetworkDetailsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserNetworkDetailsResponse
        //private UserNetworkDetailsResponse instance;

        public UserNetworkDetailsResponseTests()
        {
            // TODO uncomment below to create an instance of UserNetworkDetailsResponse
            //instance = new UserNetworkDetailsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserNetworkDetailsResponse
        /// </summary>
        [Fact]
        public void UserNetworkDetailsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserNetworkDetailsResponse
            //Assert.IsType<UserNetworkDetailsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'HnId'
        /// </summary>
        [Fact]
        public void HnIdTest()
        {
            // TODO unit test for the property 'HnId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AdditionalDescription'
        /// </summary>
        [Fact]
        public void AdditionalDescriptionTest()
        {
            // TODO unit test for the property 'AdditionalDescription'
        }

        /// <summary>
        /// Test the property 'OrganisationName'
        /// </summary>
        [Fact]
        public void OrganisationNameTest()
        {
            // TODO unit test for the property 'OrganisationName'
        }

        /// <summary>
        /// Test the property 'OrgId'
        /// </summary>
        [Fact]
        public void OrgIdTest()
        {
            // TODO unit test for the property 'OrgId'
        }
    }
}
