// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines ContributorRole
    /// </summary>
    public enum ContributorRole
    {
        /// <summary>
        /// Enum DesignatedDutyHolder for value: DesignatedDutyHolder
        /// </summary>
        DesignatedDutyHolder = 1,

        /// <summary>
        /// Enum Contributor for value: Contributor
        /// </summary>
        Contributor = 2,

        /// <summary>
        /// Enum Assessor for value: Assessor
        /// </summary>
        Assessor = 3,

        /// <summary>
        /// Enum Certifier for value: Certifier
        /// </summary>
        Certifier = 4,

        /// <summary>
        /// Enum NetworkManager for value: NetworkManager
        /// </summary>
        NetworkManager = 5,

        /// <summary>
        /// Enum ResponsibleParty for value: ResponsibleParty
        /// </summary>
        ResponsibleParty = 6
    }

    /// <summary>
    /// Converts <see cref="ContributorRole"/> to and from the JSON value
    /// </summary>
    public static class ContributorRoleValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ContributorRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ContributorRole FromString(string value)
        {
            if (value.Equals("DesignatedDutyHolder"))
                return ContributorRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return ContributorRole.Contributor;

            if (value.Equals("Assessor"))
                return ContributorRole.Assessor;

            if (value.Equals("Certifier"))
                return ContributorRole.Certifier;

            if (value.Equals("NetworkManager"))
                return ContributorRole.NetworkManager;

            if (value.Equals("ResponsibleParty"))
                return ContributorRole.ResponsibleParty;

            throw new NotImplementedException($"Could not convert value to type ContributorRole: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ContributorRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ContributorRole? FromStringOrDefault(string value)
        {
            if (value.Equals("DesignatedDutyHolder"))
                return ContributorRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return ContributorRole.Contributor;

            if (value.Equals("Assessor"))
                return ContributorRole.Assessor;

            if (value.Equals("Certifier"))
                return ContributorRole.Certifier;

            if (value.Equals("NetworkManager"))
                return ContributorRole.NetworkManager;

            if (value.Equals("ResponsibleParty"))
                return ContributorRole.ResponsibleParty;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ContributorRole"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ContributorRole value)
        {
            if (value == ContributorRole.DesignatedDutyHolder)
                return "DesignatedDutyHolder";

            if (value == ContributorRole.Contributor)
                return "Contributor";

            if (value == ContributorRole.Assessor)
                return "Assessor";

            if (value == ContributorRole.Certifier)
                return "Certifier";

            if (value == ContributorRole.NetworkManager)
                return "NetworkManager";

            if (value == ContributorRole.ResponsibleParty)
                return "ResponsibleParty";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ContributorRole"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ContributorRoleJsonConverter : JsonConverter<ContributorRole>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ContributorRole Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ContributorRole? result = rawValue == null
                ? null
                : ContributorRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ContributorRole to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contributorRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ContributorRole contributorRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(contributorRole.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ContributorRole"/>
    /// </summary>
    public class ContributorRoleNullableJsonConverter : JsonConverter<ContributorRole?>
    {
        /// <summary>
        /// Returns a ContributorRole from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ContributorRole? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ContributorRole? result = rawValue == null
                ? null
                : ContributorRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="contributorRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ContributorRole? contributorRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(contributorRole?.ToString() ?? "null");
        }
    }
}
