// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines NullableOfUserRole
    /// </summary>
    public enum NullableOfUserRole
    {
        /// <summary>
        /// Enum ResponsibleParty for value: ResponsibleParty
        /// </summary>
        ResponsibleParty = 1,

        /// <summary>
        /// Enum NetworkManager for value: NetworkManager
        /// </summary>
        NetworkManager = 2,

        /// <summary>
        /// Enum DesignatedDutyHolder for value: DesignatedDutyHolder
        /// </summary>
        DesignatedDutyHolder = 3,

        /// <summary>
        /// Enum Contributor for value: Contributor
        /// </summary>
        Contributor = 4,

        /// <summary>
        /// Enum Assessor for value: Assessor
        /// </summary>
        Assessor = 5,

        /// <summary>
        /// Enum Certifier for value: Certifier
        /// </summary>
        Certifier = 6
    }

    /// <summary>
    /// Converts <see cref="NullableOfUserRole"/> to and from the JSON value
    /// </summary>
    public static class NullableOfUserRoleValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="NullableOfUserRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullableOfUserRole FromString(string value)
        {
            if (value.Equals("ResponsibleParty"))
                return NullableOfUserRole.ResponsibleParty;

            if (value.Equals("NetworkManager"))
                return NullableOfUserRole.NetworkManager;

            if (value.Equals("DesignatedDutyHolder"))
                return NullableOfUserRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return NullableOfUserRole.Contributor;

            if (value.Equals("Assessor"))
                return NullableOfUserRole.Assessor;

            if (value.Equals("Certifier"))
                return NullableOfUserRole.Certifier;

            throw new NotImplementedException($"Could not convert value to type NullableOfUserRole: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="NullableOfUserRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullableOfUserRole? FromStringOrDefault(string value)
        {
            if (value.Equals("ResponsibleParty"))
                return NullableOfUserRole.ResponsibleParty;

            if (value.Equals("NetworkManager"))
                return NullableOfUserRole.NetworkManager;

            if (value.Equals("DesignatedDutyHolder"))
                return NullableOfUserRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return NullableOfUserRole.Contributor;

            if (value.Equals("Assessor"))
                return NullableOfUserRole.Assessor;

            if (value.Equals("Certifier"))
                return NullableOfUserRole.Certifier;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="NullableOfUserRole"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(NullableOfUserRole value)
        {
            if (value == NullableOfUserRole.ResponsibleParty)
                return "ResponsibleParty";

            if (value == NullableOfUserRole.NetworkManager)
                return "NetworkManager";

            if (value == NullableOfUserRole.DesignatedDutyHolder)
                return "DesignatedDutyHolder";

            if (value == NullableOfUserRole.Contributor)
                return "Contributor";

            if (value == NullableOfUserRole.Assessor)
                return "Assessor";

            if (value == NullableOfUserRole.Certifier)
                return "Certifier";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullableOfUserRole"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class NullableOfUserRoleJsonConverter : JsonConverter<NullableOfUserRole>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullableOfUserRole Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullableOfUserRole? result = rawValue == null
                ? null
                : NullableOfUserRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NullableOfUserRole to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullableOfUserRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullableOfUserRole nullableOfUserRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(nullableOfUserRole.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullableOfUserRole"/>
    /// </summary>
    public class NullableOfUserRoleNullableJsonConverter : JsonConverter<NullableOfUserRole?>
    {
        /// <summary>
        /// Returns a NullableOfUserRole from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullableOfUserRole? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullableOfUserRole? result = rawValue == null
                ? null
                : NullableOfUserRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullableOfUserRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullableOfUserRole? nullableOfUserRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(nullableOfUserRole?.ToString() ?? "null");
        }
    }
}
