// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// PagedResultOfUserNetworkDetailsResponse
    /// </summary>
    public partial class PagedResultOfUserNetworkDetailsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PagedResultOfUserNetworkDetailsResponse" /> class.
        /// </summary>
        /// <param name="items">items</param>
        /// <param name="pageNumber">pageNumber</param>
        /// <param name="pageSize">pageSize</param>
        /// <param name="totalCount">totalCount</param>
        /// <param name="totalPages">totalPages</param>
        /// <param name="hasPreviousPage">hasPreviousPage</param>
        /// <param name="hasNextPage">hasNextPage</param>
        [JsonConstructor]
        public PagedResultOfUserNetworkDetailsResponse(Option<List<UserNetworkDetailsResponse>?> items = default, Option<int?> pageNumber = default, Option<int?> pageSize = default, Option<int?> totalCount = default, Option<int?> totalPages = default, Option<bool?> hasPreviousPage = default, Option<bool?> hasNextPage = default)
        {
            ItemsOption = items;
            PageNumberOption = pageNumber;
            PageSizeOption = pageSize;
            TotalCountOption = totalCount;
            TotalPagesOption = totalPages;
            HasPreviousPageOption = hasPreviousPage;
            HasNextPageOption = hasNextPage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Items
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<UserNetworkDetailsResponse>?> ItemsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<UserNetworkDetailsResponse>? Items { get { return this.ItemsOption; } set { this.ItemsOption = new(value); } }

        /// <summary>
        /// Used to track the state of PageNumber
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageNumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageNumber
        /// </summary>
        [JsonPropertyName("pageNumber")]
        public int? PageNumber { get { return this.PageNumberOption; } set { this.PageNumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of PageSize
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PageSizeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [JsonPropertyName("pageSize")]
        public int? PageSize { get { return this.PageSizeOption; } set { this.PageSizeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalCount
        /// </summary>
        [JsonPropertyName("totalCount")]
        public int? TotalCount { get { return this.TotalCountOption; } set { this.TotalCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalPages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalPagesOption { get; private set; }

        /// <summary>
        /// Gets or Sets TotalPages
        /// </summary>
        [JsonPropertyName("totalPages")]
        public int? TotalPages { get { return this.TotalPagesOption; } set { this.TotalPagesOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasPreviousPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasPreviousPageOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasPreviousPage
        /// </summary>
        [JsonPropertyName("hasPreviousPage")]
        public bool? HasPreviousPage { get { return this.HasPreviousPageOption; } set { this.HasPreviousPageOption = new(value); } }

        /// <summary>
        /// Used to track the state of HasNextPage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HasNextPageOption { get; private set; }

        /// <summary>
        /// Gets or Sets HasNextPage
        /// </summary>
        [JsonPropertyName("hasNextPage")]
        public bool? HasNextPage { get { return this.HasNextPageOption; } set { this.HasNextPageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PagedResultOfUserNetworkDetailsResponse {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  PageNumber: ").Append(PageNumber).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("  HasPreviousPage: ").Append(HasPreviousPage).Append("\n");
            sb.Append("  HasNextPage: ").Append(HasNextPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PagedResultOfUserNetworkDetailsResponse" />
    /// </summary>
    public class PagedResultOfUserNetworkDetailsResponseJsonConverter : JsonConverter<PagedResultOfUserNetworkDetailsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PagedResultOfUserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PagedResultOfUserNetworkDetailsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<UserNetworkDetailsResponse>?> items = default;
            Option<int?> pageNumber = default;
            Option<int?> pageSize = default;
            Option<int?> totalCount = default;
            Option<int?> totalPages = default;
            Option<bool?> hasPreviousPage = default;
            Option<bool?> hasNextPage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "items":
                            items = new Option<List<UserNetworkDetailsResponse>?>(JsonSerializer.Deserialize<List<UserNetworkDetailsResponse>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "pageNumber":
                            pageNumber = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "pageSize":
                            pageSize = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "totalCount":
                            totalCount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "totalPages":
                            totalPages = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "hasPreviousPage":
                            hasPreviousPage = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "hasNextPage":
                            hasNextPage = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (pageNumber.IsSet && pageNumber.Value == null)
                throw new ArgumentNullException(nameof(pageNumber), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (pageSize.IsSet && pageSize.Value == null)
                throw new ArgumentNullException(nameof(pageSize), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (totalCount.IsSet && totalCount.Value == null)
                throw new ArgumentNullException(nameof(totalCount), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (totalPages.IsSet && totalPages.Value == null)
                throw new ArgumentNullException(nameof(totalPages), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (hasPreviousPage.IsSet && hasPreviousPage.Value == null)
                throw new ArgumentNullException(nameof(hasPreviousPage), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            if (hasNextPage.IsSet && hasNextPage.Value == null)
                throw new ArgumentNullException(nameof(hasNextPage), "Property is not nullable for class PagedResultOfUserNetworkDetailsResponse.");

            return new PagedResultOfUserNetworkDetailsResponse(items, pageNumber, pageSize, totalCount, totalPages, hasPreviousPage, hasNextPage);
        }

        /// <summary>
        /// Serializes a <see cref="PagedResultOfUserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagedResultOfUserNetworkDetailsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PagedResultOfUserNetworkDetailsResponse pagedResultOfUserNetworkDetailsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, pagedResultOfUserNetworkDetailsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PagedResultOfUserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pagedResultOfUserNetworkDetailsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PagedResultOfUserNetworkDetailsResponse pagedResultOfUserNetworkDetailsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (pagedResultOfUserNetworkDetailsResponse.ItemsOption.IsSet && pagedResultOfUserNetworkDetailsResponse.Items == null)
                throw new ArgumentNullException(nameof(pagedResultOfUserNetworkDetailsResponse.Items), "Property is required for class PagedResultOfUserNetworkDetailsResponse.");

            if (pagedResultOfUserNetworkDetailsResponse.ItemsOption.IsSet)
            {
                writer.WritePropertyName("items");
                JsonSerializer.Serialize(writer, pagedResultOfUserNetworkDetailsResponse.Items, jsonSerializerOptions);
            }
            if (pagedResultOfUserNetworkDetailsResponse.PageNumberOption.IsSet)
                writer.WriteNumber("pageNumber", pagedResultOfUserNetworkDetailsResponse.PageNumberOption.Value!.Value);

            if (pagedResultOfUserNetworkDetailsResponse.PageSizeOption.IsSet)
                writer.WriteNumber("pageSize", pagedResultOfUserNetworkDetailsResponse.PageSizeOption.Value!.Value);

            if (pagedResultOfUserNetworkDetailsResponse.TotalCountOption.IsSet)
                writer.WriteNumber("totalCount", pagedResultOfUserNetworkDetailsResponse.TotalCountOption.Value!.Value);

            if (pagedResultOfUserNetworkDetailsResponse.TotalPagesOption.IsSet)
                writer.WriteNumber("totalPages", pagedResultOfUserNetworkDetailsResponse.TotalPagesOption.Value!.Value);

            if (pagedResultOfUserNetworkDetailsResponse.HasPreviousPageOption.IsSet)
                writer.WriteBoolean("hasPreviousPage", pagedResultOfUserNetworkDetailsResponse.HasPreviousPageOption.Value!.Value);

            if (pagedResultOfUserNetworkDetailsResponse.HasNextPageOption.IsSet)
                writer.WriteBoolean("hasNextPage", pagedResultOfUserNetworkDetailsResponse.HasNextPageOption.Value!.Value);
        }
    }
}
