// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// Defines UserRole
    /// </summary>
    public enum UserRole
    {
        /// <summary>
        /// Enum ResponsibleParty for value: ResponsibleParty
        /// </summary>
        ResponsibleParty = 1,

        /// <summary>
        /// Enum NetworkManager for value: NetworkManager
        /// </summary>
        NetworkManager = 2,

        /// <summary>
        /// Enum DesignatedDutyHolder for value: DesignatedDutyHolder
        /// </summary>
        DesignatedDutyHolder = 3,

        /// <summary>
        /// Enum Contributor for value: Contributor
        /// </summary>
        Contributor = 4,

        /// <summary>
        /// Enum Assessor for value: Assessor
        /// </summary>
        Assessor = 5,

        /// <summary>
        /// Enum Certifier for value: Certifier
        /// </summary>
        Certifier = 6
    }

    /// <summary>
    /// Converts <see cref="UserRole"/> to and from the JSON value
    /// </summary>
    public static class UserRoleValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="UserRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static UserRole FromString(string value)
        {
            if (value.Equals("ResponsibleParty"))
                return UserRole.ResponsibleParty;

            if (value.Equals("NetworkManager"))
                return UserRole.NetworkManager;

            if (value.Equals("DesignatedDutyHolder"))
                return UserRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return UserRole.Contributor;

            if (value.Equals("Assessor"))
                return UserRole.Assessor;

            if (value.Equals("Certifier"))
                return UserRole.Certifier;

            throw new NotImplementedException($"Could not convert value to type UserRole: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="UserRole"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static UserRole? FromStringOrDefault(string value)
        {
            if (value.Equals("ResponsibleParty"))
                return UserRole.ResponsibleParty;

            if (value.Equals("NetworkManager"))
                return UserRole.NetworkManager;

            if (value.Equals("DesignatedDutyHolder"))
                return UserRole.DesignatedDutyHolder;

            if (value.Equals("Contributor"))
                return UserRole.Contributor;

            if (value.Equals("Assessor"))
                return UserRole.Assessor;

            if (value.Equals("Certifier"))
                return UserRole.Certifier;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="UserRole"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(UserRole value)
        {
            if (value == UserRole.ResponsibleParty)
                return "ResponsibleParty";

            if (value == UserRole.NetworkManager)
                return "NetworkManager";

            if (value == UserRole.DesignatedDutyHolder)
                return "DesignatedDutyHolder";

            if (value == UserRole.Contributor)
                return "Contributor";

            if (value == UserRole.Assessor)
                return "Assessor";

            if (value == UserRole.Certifier)
                return "Certifier";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserRole"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class UserRoleJsonConverter : JsonConverter<UserRole>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override UserRole Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            UserRole? result = rawValue == null
                ? null
                : UserRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the UserRole to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, UserRole userRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(userRole.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserRole"/>
    /// </summary>
    public class UserRoleNullableJsonConverter : JsonConverter<UserRole?>
    {
        /// <summary>
        /// Returns a UserRole from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override UserRole? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            UserRole? result = rawValue == null
                ? null
                : UserRoleValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userRole"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, UserRole? userRole, JsonSerializerOptions options)
        {
            writer.WriteStringValue(userRole?.ToString() ?? "null");
        }
    }
}
