// <auto-generated>
/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using HNTAS.Api.Client.Client;

namespace HNTAS.Api.Client.Model
{
    /// <summary>
    /// UserNetworkDetailsResponse
    /// </summary>
    public partial class UserNetworkDetailsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserNetworkDetailsResponse" /> class.
        /// </summary>
        /// <param name="hnId">hnId</param>
        /// <param name="name">name</param>
        /// <param name="additionalDescription">additionalDescription</param>
        /// <param name="organisationName">organisationName</param>
        /// <param name="orgId">orgId</param>
        [JsonConstructor]
        public UserNetworkDetailsResponse(Option<string?> hnId = default, Option<string?> name = default, Option<string?> additionalDescription = default, Option<string?> organisationName = default, Option<string?> orgId = default)
        {
            HnIdOption = hnId;
            NameOption = name;
            AdditionalDescriptionOption = additionalDescription;
            OrganisationNameOption = organisationName;
            OrgIdOption = orgId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of HnId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> HnIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HnId
        /// </summary>
        [JsonPropertyName("hnId")]
        public string? HnId { get { return this.HnIdOption; } set { this.HnIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of AdditionalDescription
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AdditionalDescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets AdditionalDescription
        /// </summary>
        [JsonPropertyName("additionalDescription")]
        public string? AdditionalDescription { get { return this.AdditionalDescriptionOption; } set { this.AdditionalDescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrganisationName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrganisationNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrganisationName
        /// </summary>
        [JsonPropertyName("organisationName")]
        public string? OrganisationName { get { return this.OrganisationNameOption; } set { this.OrganisationNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrgId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrgIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrgId
        /// </summary>
        [JsonPropertyName("orgId")]
        public string? OrgId { get { return this.OrgIdOption; } set { this.OrgIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserNetworkDetailsResponse {\n");
            sb.Append("  HnId: ").Append(HnId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AdditionalDescription: ").Append(AdditionalDescription).Append("\n");
            sb.Append("  OrganisationName: ").Append(OrganisationName).Append("\n");
            sb.Append("  OrgId: ").Append(OrgId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UserNetworkDetailsResponse" />
    /// </summary>
    public class UserNetworkDetailsResponseJsonConverter : JsonConverter<UserNetworkDetailsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="UserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UserNetworkDetailsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> hnId = default;
            Option<string?> name = default;
            Option<string?> additionalDescription = default;
            Option<string?> organisationName = default;
            Option<string?> orgId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hnId":
                            hnId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "additionalDescription":
                            additionalDescription = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "organisationName":
                            organisationName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "orgId":
                            orgId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (hnId.IsSet && hnId.Value == null)
                throw new ArgumentNullException(nameof(hnId), "Property is not nullable for class UserNetworkDetailsResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UserNetworkDetailsResponse.");

            return new UserNetworkDetailsResponse(hnId, name, additionalDescription, organisationName, orgId);
        }

        /// <summary>
        /// Serializes a <see cref="UserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userNetworkDetailsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UserNetworkDetailsResponse userNetworkDetailsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, userNetworkDetailsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UserNetworkDetailsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="userNetworkDetailsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UserNetworkDetailsResponse userNetworkDetailsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (userNetworkDetailsResponse.HnIdOption.IsSet && userNetworkDetailsResponse.HnId == null)
                throw new ArgumentNullException(nameof(userNetworkDetailsResponse.HnId), "Property is required for class UserNetworkDetailsResponse.");

            if (userNetworkDetailsResponse.NameOption.IsSet && userNetworkDetailsResponse.Name == null)
                throw new ArgumentNullException(nameof(userNetworkDetailsResponse.Name), "Property is required for class UserNetworkDetailsResponse.");

            if (userNetworkDetailsResponse.HnIdOption.IsSet)
                writer.WriteString("hnId", userNetworkDetailsResponse.HnId);

            if (userNetworkDetailsResponse.NameOption.IsSet)
                writer.WriteString("name", userNetworkDetailsResponse.Name);

            if (userNetworkDetailsResponse.AdditionalDescriptionOption.IsSet)
                if (userNetworkDetailsResponse.AdditionalDescriptionOption.Value != null)
                    writer.WriteString("additionalDescription", userNetworkDetailsResponse.AdditionalDescription);
                else
                    writer.WriteNull("additionalDescription");

            if (userNetworkDetailsResponse.OrganisationNameOption.IsSet)
                if (userNetworkDetailsResponse.OrganisationNameOption.Value != null)
                    writer.WriteString("organisationName", userNetworkDetailsResponse.OrganisationName);
                else
                    writer.WriteNull("organisationName");

            if (userNetworkDetailsResponse.OrgIdOption.IsSet)
                if (userNetworkDetailsResponse.OrgIdOption.Value != null)
                    writer.WriteString("orgId", userNetworkDetailsResponse.OrgId);
                else
                    writer.WriteNull("orgId");
        }
    }
}
