/*
 * HNTAS.Core.Api | HNTAS.Core.Api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using HNTAS.Api.Client.Api;
using HNTAS.Api.Client.Model;

namespace HNTAS.Api.Client.Client
{
    /// <summary>
    /// Provides hosting configuration for HNTAS.Api.Client
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AddInvitationRequestJsonConverter());
            _jsonOptions.Converters.Add(new AddressJsonConverter());
            _jsonOptions.Converters.Add(new AggregatedKpiJsonConverter());
            _jsonOptions.Converters.Add(new ArmsPowerBiReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new ArmsPowerBiUserReportResponseJsonConverter());
            _jsonOptions.Converters.Add(new AssessmentPlanJsonConverter());
            _jsonOptions.Converters.Add(new AssessmentPlanResponseJsonConverter());
            _jsonOptions.Converters.Add(new AssessorAssessmentJsonConverter());
            _jsonOptions.Converters.Add(new AssessorAssessmentForElementJsonConverter());
            _jsonOptions.Converters.Add(new AssessorSearchResultJsonConverter());
            _jsonOptions.Converters.Add(new AssignedAssessorJsonConverter());
            _jsonOptions.Converters.Add(new AssignedAssessorRequestJsonConverter());
            _jsonOptions.Converters.Add(new AssignedAssessorResponseJsonConverter());
            _jsonOptions.Converters.Add(new AuditLogJsonConverter());
            _jsonOptions.Converters.Add(new AuditLogRequestJsonConverter());
            _jsonOptions.Converters.Add(new AuditLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new BackgroundJsonConverter());
            _jsonOptions.Converters.Add(new BoilerInputJsonConverter());
            _jsonOptions.Converters.Add(new CCKpiValueRequestJsonConverter());
            _jsonOptions.Converters.Add(new CarbonCalculatorConfigRequestJsonConverter());
            _jsonOptions.Converters.Add(new CarbonCalculatorConfigResponseJsonConverter());
            _jsonOptions.Converters.Add(new CarbonCalculatorRequestJsonConverter());
            _jsonOptions.Converters.Add(new CarbonCalculatorResponseJsonConverter());
            _jsonOptions.Converters.Add(new CarbonInputUiDisplayJsonConverter());
            _jsonOptions.Converters.Add(new ChpInputJsonConverter());
            _jsonOptions.Converters.Add(new ConfigDefaultJsonConverter());
            _jsonOptions.Converters.Add(new ConnectionTypeJsonConverter());
            _jsonOptions.Converters.Add(new ConnectionTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new ContributorRoleJsonConverter());
            _jsonOptions.Converters.Add(new ContributorRoleNullableJsonConverter());
            _jsonOptions.Converters.Add(new CountryAndTerritoryJsonConverter());
            _jsonOptions.Converters.Add(new CreateFeedbackRequestJsonConverter());
            _jsonOptions.Converters.Add(new DesignConstructionLogJsonConverter());
            _jsonOptions.Converters.Add(new DesignConstructionLogResponseJsonConverter());
            _jsonOptions.Converters.Add(new ECDetailsJsonConverter());
            _jsonOptions.Converters.Add(new ElementJsonConverter());
            _jsonOptions.Converters.Add(new ElementGroupJsonConverter());
            _jsonOptions.Converters.Add(new ElementGroupDtoJsonConverter());
            _jsonOptions.Converters.Add(new ElementSoaAssignAssessorRequestJsonConverter());
            _jsonOptions.Converters.Add(new ElementSoaAssignAssessorRequestForExistingNetworkJsonConverter());
            _jsonOptions.Converters.Add(new ElementSoaStatusUpdateRequestJsonConverter());
            _jsonOptions.Converters.Add(new ElementSoaStatusUpdateRequestForExistingNetworkJsonConverter());
            _jsonOptions.Converters.Add(new ElementTypeInShortJsonConverter());
            _jsonOptions.Converters.Add(new ElementTypeInShortNullableJsonConverter());
            _jsonOptions.Converters.Add(new EnergyJsonConverter());
            _jsonOptions.Converters.Add(new EnergyCentreDetailsJsonConverter());
            _jsonOptions.Converters.Add(new EnumItemResponseJsonConverter());
            _jsonOptions.Converters.Add(new ExistingNetworkRequestJsonConverter());
            _jsonOptions.Converters.Add(new ExistingNetworkResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkConnectionsJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkDashboardResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkDashboardRowJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkDetailsResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkElementJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkElementResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkElementTypeJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkElementTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkExternalResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkInfoJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkTypeJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new HeatNetworkUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new HeatPumpInputJsonConverter());
            _jsonOptions.Converters.Add(new HnRoleMappingJsonConverter());
            _jsonOptions.Converters.Add(new ImportResultJsonConverter());
            _jsonOptions.Converters.Add(new InitialUserRegistrationRequestJsonConverter());
            _jsonOptions.Converters.Add(new InvitationStatusJsonConverter());
            _jsonOptions.Converters.Add(new InvitationStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new InvitedUserRequestJsonConverter());
            _jsonOptions.Converters.Add(new InvitedUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new JourneyDataResponseJsonConverter());
            _jsonOptions.Converters.Add(new KpiConfigRequestJsonConverter());
            _jsonOptions.Converters.Add(new KpiConfigRequestV2JsonConverter());
            _jsonOptions.Converters.Add(new KpiConfigResponseJsonConverter());
            _jsonOptions.Converters.Add(new KpiConfigResponseV2JsonConverter());
            _jsonOptions.Converters.Add(new KpiDetailDtoJsonConverter());
            _jsonOptions.Converters.Add(new KpiHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new KpiMetadataJsonConverter());
            _jsonOptions.Converters.Add(new KpiRuleJsonConverter());
            _jsonOptions.Converters.Add(new KpiSubmissionApiErrorJsonConverter());
            _jsonOptions.Converters.Add(new KpiSubmissionApiErrorResponseJsonConverter());
            _jsonOptions.Converters.Add(new KpiSubmissionRequestJsonConverter());
            _jsonOptions.Converters.Add(new KpiSubmissionRequestV2JsonConverter());
            _jsonOptions.Converters.Add(new KpiThresholdRuleJsonConverter());
            _jsonOptions.Converters.Add(new KpiValueAggregatedRequestJsonConverter());
            _jsonOptions.Converters.Add(new KpiValueRequestJsonConverter());
            _jsonOptions.Converters.Add(new ManagedUserResponseJsonConverter());
            _jsonOptions.Converters.Add(new MeteringAndMonitoringStrategyJsonConverter());
            _jsonOptions.Converters.Add(new MeteringAndMonitoringStrategyResponseJsonConverter());
            _jsonOptions.Converters.Add(new MilestoneJsonConverter());
            _jsonOptions.Converters.Add(new MilestoneNullableJsonConverter());
            _jsonOptions.Converters.Add(new NetworkDetailsStatusJsonConverter());
            _jsonOptions.Converters.Add(new NetworkDetailsStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new NetworkDetailsUploadedDocumentJsonConverter());
            _jsonOptions.Converters.Add(new NetworkElementRequestJsonConverter());
            _jsonOptions.Converters.Add(new NetworkElementsJsonConverter());
            _jsonOptions.Converters.Add(new NetworkElements2JsonConverter());
            _jsonOptions.Converters.Add(new NetworkElementsResponseJsonConverter());
            _jsonOptions.Converters.Add(new NetworkTypeResponseJsonConverter());
            _jsonOptions.Converters.Add(new NetworkTypeSelectionJsonConverter());
            _jsonOptions.Converters.Add(new NotificationHistoryDataJsonConverter());
            _jsonOptions.Converters.Add(new NotificationHistoryRequestJsonConverter());
            _jsonOptions.Converters.Add(new NotificationHistoryResponseJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfHeatNetworkTypeJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfHeatNetworkTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfMilestoneJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfMilestoneNullableJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfPreferredContactTypeJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfPreferredContactTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfSoaStageJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfSoaStageNullableJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfUserRoleJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfUserRoleNullableJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfUserStatusJsonConverter());
            _jsonOptions.Converters.Add(new NullableOfUserStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new OfgemDataModelForNotificationJsonConverter());
            _jsonOptions.Converters.Add(new OrgDetailsJsonConverter());
            _jsonOptions.Converters.Add(new OrganisationJsonConverter());
            _jsonOptions.Converters.Add(new OrganisationRequestJsonConverter());
            _jsonOptions.Converters.Add(new OrganisationResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrganisationTypeJsonConverter());
            _jsonOptions.Converters.Add(new OrganisationTypeNullableJsonConverter());
            _jsonOptions.Converters.Add(new PagedResultOfUserNetworkDetailsResponseJsonConverter());
            _jsonOptions.Converters.Add(new ProblemDetailsJsonConverter());
            _jsonOptions.Converters.Add(new RecoveredInputJsonConverter());
            _jsonOptions.Converters.Add(new RegisteredAddressJsonConverter());
            _jsonOptions.Converters.Add(new RegisteredAddress2JsonConverter());
            _jsonOptions.Converters.Add(new RegistrationSourceJsonConverter());
            _jsonOptions.Converters.Add(new RegistrationSourceNullableJsonConverter());
            _jsonOptions.Converters.Add(new RegistrationSource2JsonConverter());
            _jsonOptions.Converters.Add(new RegistrationSource2NullableJsonConverter());
            _jsonOptions.Converters.Add(new SendInvitationEmailRequestJsonConverter());
            _jsonOptions.Converters.Add(new SoaJsonConverter());
            _jsonOptions.Converters.Add(new SoaAssessorJsonConverter());
            _jsonOptions.Converters.Add(new SoaAssessorExistingNetworkJsonConverter());
            _jsonOptions.Converters.Add(new SoaJourneyDataJsonConverter());
            _jsonOptions.Converters.Add(new SoaMilestoneJsonConverter());
            _jsonOptions.Converters.Add(new SoaPhaseJsonConverter());
            _jsonOptions.Converters.Add(new SoaPhaseNullableJsonConverter());
            _jsonOptions.Converters.Add(new SoaResponseJsonConverter());
            _jsonOptions.Converters.Add(new SoaResponse2JsonConverter());
            _jsonOptions.Converters.Add(new SoaStageJsonConverter());
            _jsonOptions.Converters.Add(new SoaStageNullableJsonConverter());
            _jsonOptions.Converters.Add(new SoaStagesJsonConverter());
            _jsonOptions.Converters.Add(new SoaStatusJsonConverter());
            _jsonOptions.Converters.Add(new SoaStatusNullableJsonConverter());
            _jsonOptions.Converters.Add(new SoaStatusWithCountJsonConverter());
            _jsonOptions.Converters.Add(new SoaStatusWithCountExistingNetworkJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSoaStatusRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserDetailsRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserOrgIdRequestJsonConverter());
            _jsonOptions.Converters.Add(new UpdateUserOrganisationRequestJsonConverter());
            _jsonOptions.Converters.Add(new UploadedAssessmentDocumentResponseJsonConverter());
            _jsonOptions.Converters.Add(new UploadedAssessorDocumentResponseJsonConverter());
            _jsonOptions.Converters.Add(new UploadedCertifierDocumentResponseJsonConverter());
            _jsonOptions.Converters.Add(new UploadedDocumentJsonConverter());
            _jsonOptions.Converters.Add(new UploadedDocumentResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserJsonConverter());
            _jsonOptions.Converters.Add(new UserDetailsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserNetworkDetailsResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserRoleJsonConverter());
            _jsonOptions.Converters.Add(new UserRoleNullableJsonConverter());
            _jsonOptions.Converters.Add(new UserRoleDetailResponseJsonConverter());
            _jsonOptions.Converters.Add(new UserStatusJsonConverter());
            _jsonOptions.Converters.Add(new UserStatusNullableJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<ArmsApiEvents>();
            _services.AddSingleton<ArmsDashboardApiEvents>();
            _services.AddSingleton<ArmsReportApiEvents>();
            _services.AddSingleton<AssessorApiEvents>();
            _services.AddSingleton<AssignedAssessorApiEvents>();
            _services.AddSingleton<AuditApiEvents>();
            _services.AddSingleton<CarbonCalculatorApiEvents>();
            _services.AddSingleton<CountriesAndTerritoriesApiEvents>();
            _services.AddSingleton<FeedbackApiEvents>();
            _services.AddSingleton<HeatNetworksApiEvents>();
            _services.AddSingleton<ImportApiEvents>();
            _services.AddSingleton<InvitationsApiEvents>();
            _services.AddSingleton<NotificationHistoryApiEvents>();
            _services.AddSingleton<OrganisationUserApiEvents>();
            _services.AddSingleton<OrganisationsApiEvents>();
            _services.AddSingleton<SOAApiEvents>();
            _services.AddSingleton<SuperUserApiEvents>();
            _services.AddSingleton<UsersApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IArmsApi, ArmsApi>(client));
            builders.Add(_services.AddHttpClient<IArmsDashboardApi, ArmsDashboardApi>(client));
            builders.Add(_services.AddHttpClient<IArmsReportApi, ArmsReportApi>(client));
            builders.Add(_services.AddHttpClient<IAssessorApi, AssessorApi>(client));
            builders.Add(_services.AddHttpClient<IAssignedAssessorApi, AssignedAssessorApi>(client));
            builders.Add(_services.AddHttpClient<IAuditApi, AuditApi>(client));
            builders.Add(_services.AddHttpClient<ICarbonCalculatorApi, CarbonCalculatorApi>(client));
            builders.Add(_services.AddHttpClient<ICountriesAndTerritoriesApi, CountriesAndTerritoriesApi>(client));
            builders.Add(_services.AddHttpClient<IFeedbackApi, FeedbackApi>(client));
            builders.Add(_services.AddHttpClient<IHeatNetworksApi, HeatNetworksApi>(client));
            builders.Add(_services.AddHttpClient<IImportApi, ImportApi>(client));
            builders.Add(_services.AddHttpClient<IInvitationsApi, InvitationsApi>(client));
            builders.Add(_services.AddHttpClient<INotificationHistoryApi, NotificationHistoryApi>(client));
            builders.Add(_services.AddHttpClient<IOrganisationUserApi, OrganisationUserApi>(client));
            builders.Add(_services.AddHttpClient<IOrganisationsApi, OrganisationsApi>(client));
            builders.Add(_services.AddHttpClient<ISOAApi, SOAApi>(client));
            builders.Add(_services.AddHttpClient<ISuperUserApi, SuperUserApi>(client));
            builders.Add(_services.AddHttpClient<IUsersApi, UsersApi>(client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
